export interface FoodItem {
  name: string
  description: string
  category: string
  icon: string
  categoryName: string
  timestamp?: Date
}

export const categories = [
  { id: 'all', name: '全部' },
  { id: 'chinese', name: '中餐' },
  { id: 'western', name: '西餐' },
  { id: 'fastfood', name: '快餐' },
  { id: 'dessert', name: '甜点' },
  { id: 'healthy', name: '健康餐' },
]

export const foodData: FoodItem[] = [
  {
    name: '宫保鸡丁',
    description: '经典川菜，鸡肉鲜嫩，花生酥脆，配以辣椒和葱姜蒜调味',
    category: 'chinese',
    icon: 'fa-cutlery',
    categoryName: '中餐',
  },
  {
    name: '鱼香肉丝',
    description: '以鱼香调味汁得名，酸甜可口，配以猪肉丝、木耳、胡萝卜等',
    category: 'chinese',
    icon: 'fa-cutlery',
    categoryName: '中餐',
  },
  {
    name: '麻婆豆腐',
    description: '四川名菜，嫩豆腐配以麻辣鲜香的豆瓣酱酱汁，撒上花椒粉',
    category: 'chinese',
    icon: 'fa-cutlery',
    categoryName: '中餐',
  },
  {
    name: '番茄炒蛋',
    description: '国民家常菜，鸡蛋嫩滑，番茄酸甜多汁，营养美味',
    category: 'chinese',
    icon: 'fa-cutlery',
    categoryName: '中餐',
  },
  {
    name: '兰州拉面',
    description: '一清二白三红四绿五黄，汤清面韧，配上牛肉片和香菜',
    category: 'chinese',
    icon: 'fa-cutlery',
    categoryName: '中餐',
  },
  {
    name: '饺子',
    description: '传统面食，皮薄馅大，可蒸可煮，常配醋食用',
    category: 'chinese',
    icon: 'fa-cutlery',
    categoryName: '中餐',
  },
  {
    name: '包子',
    description: '发面做皮，包裹各种馅料，松软可口，早餐佳品',
    category: 'chinese',
    icon: 'fa-cutlery',
    categoryName: '中餐',
  },
  {
    name: '寿司',
    description: '新鲜生鱼片与醋饭的完美结合，多种口味选择',
    category: 'chinese',
    icon: 'fa-cutlery',
    categoryName: '中餐',
  },
  {
    name: '烤鸭',
    description: '皮酥肉嫩的北京烤鸭，配以薄饼、葱丝和甜面酱',
    category: 'chinese',
    icon: 'fa-cutlery',
    categoryName: '中餐',
  },
  {
    name: '炒饭',
    description: '米饭与鸡蛋、火腿、蔬菜等炒制而成，香糯可口',
    category: 'chinese',
    icon: 'fa-fire',
    categoryName: '中餐',
  },
  {
    name: '牛排',
    description: '精选牛肉煎制，外焦里嫩，搭配黑椒汁或蘑菇酱',
    category: 'western',
    icon: 'fa-cutlery',
    categoryName: '西餐',
  },
  {
    name: '披萨',
    description: '薄脆饼底，配以番茄酱、mozzarella 奶酪和各种 toppings',
    category: 'western',
    icon: 'fa-cutlery',
    categoryName: '西餐',
  },
  {
    name: '意面',
    description: '意大利面搭配番茄酱和肉酱，撒上帕玛森奶酪',
    category: 'western',
    icon: 'fa-cutlery',
    categoryName: '西餐',
  },
  {
    name: '三明治',
    description: '面包夹火腿、鸡蛋、蔬菜等，简单快捷的西式食品',
    category: 'western',
    icon: 'fa-cutlery',
    categoryName: '西餐',
  },
  {
    name: '沙拉',
    description: '新鲜蔬菜、水果、坚果和鸡胸肉，搭配橄榄油醋汁',
    category: 'western',
    icon: 'fa-leaf',
    categoryName: '西餐',
  },
  {
    name: '薯条',
    description: '马铃薯切条油炸而成，外酥里嫩，常配番茄酱',
    category: 'western',
    icon: 'fa-cutlery',
    categoryName: '西餐',
  },
  {
    name: '汉堡',
    description: '双层牛肉饼，搭配芝士、生菜、番茄和特制酱料',
    category: 'western',
    icon: 'fa-cutlery',
    categoryName: '西餐',
  },
  {
    name: '炸鸡',
    description: '外酥里嫩的炸鸡，可搭配蜂蜜芥末或番茄酱',
    category: 'fastfood',
    icon: 'fa-cutlery',
    categoryName: '快餐',
  },
  {
    name: '麻辣烫',
    description: '自选食材，麻辣鲜香的汤底，暖心暖胃',
    category: 'fastfood',
    icon: 'fa-fire',
    categoryName: '快餐',
  },
  {
    name: '手抓饼',
    description: '酥脆的面饼，可加鸡蛋、火腿、生菜等配料',
    category: 'fastfood',
    icon: 'fa-cutlery',
    categoryName: '快餐',
  },
  {
    name: '油条',
    description: '传统油炸食品，外酥内软，常配豆浆食用',
    category: 'fastfood',
    icon: 'fa-cutlery',
    categoryName: '快餐',
  },
  {
    name: '豆浆',
    description: '黄豆磨制而成的饮品，营养丰富，早餐好搭档',
    category: 'fastfood',
    icon: 'fa-coffee',
    categoryName: '快餐',
  },
  {
    name: '煎饼果子',
    description: '绿豆面摊成薄饼，加鸡蛋、薄脆、酱料等卷起',
    category: 'fastfood',
    icon: 'fa-cutlery',
    categoryName: '快餐',
  },
  {
    name: '烤串',
    description: '肉类或蔬菜穿成串烤制，撒上孜然和辣椒粉',
    category: 'fastfood',
    icon: 'fa-fire',
    categoryName: '快餐',
  },
  {
    name: '酸辣粉',
    description: '红薯粉配以酸辣汤底，加上花生、香菜等配料',
    category: 'fastfood',
    icon: 'fa-cutlery',
    categoryName: '快餐',
  },
  {
    name: '螺蛳粉',
    description: '广西特色小吃，酸笋汤底，配以米粉和多种配料',
    category: 'fastfood',
    icon: 'fa-cutlery',
    categoryName: '快餐',
  },
  {
    name: '炸鸡米花',
    description: '鸡肉切成小块裹粉炸制，外酥里嫩，可做零食',
    category: 'fastfood',
    icon: 'fa-cutlery',
    categoryName: '快餐',
  },
  {
    name: '提拉米苏',
    description: '意大利经典甜点，咖啡酒浸泡的手指饼干与马斯卡彭奶酪层层叠加',
    category: 'dessert',
    icon: 'fa-birthday-cake',
    categoryName: '甜点',
  },
  {
    name: '冰淇淋',
    description: '丝滑细腻的冰淇淋，多种口味可选',
    category: 'dessert',
    icon: 'fa-birthday-cake',
    categoryName: '甜点',
  },
  {
    name: '水果捞',
    description: '多种新鲜水果搭配酸奶或椰奶，清爽健康',
    category: 'dessert',
    icon: 'fa-apple',
    categoryName: '甜点',
  },
  {
    name: '蛋糕',
    description: '松软的海绵蛋糕，配以奶油和水果装饰',
    category: 'dessert',
    icon: 'fa-birthday-cake',
    categoryName: '甜点',
  },
  {
    name: '奶茶',
    description: '牛奶与茶叶混合的饮品，可加珍珠、椰果等配料',
    category: 'dessert',
    icon: 'fa-coffee',
    categoryName: '甜点',
  },
  {
    name: '蛋挞',
    description: '酥脆的挞皮，包裹嫩滑的蛋奶馅，香甜可口',
    category: 'dessert',
    icon: 'fa-birthday-cake',
    categoryName: '甜点',
  },
  {
    name: '果冻',
    description: '透明胶状甜品，多种水果口味，口感爽滑',
    category: 'dessert',
    icon: 'fa-apple',
    categoryName: '甜点',
  },
  {
    name: '巧克力',
    description: '可可豆制成的甜食，丝滑浓郁，多种口味',
    category: 'dessert',
    icon: 'fa-birthday-cake',
    categoryName: '甜点',
  },
  {
    name: '饼干',
    description: '烘焙而成的小点心，酥脆可口，适合搭配茶饮',
    category: 'dessert',
    icon: 'fa-birthday-cake',
    categoryName: '甜点',
  },
  {
    name: '蔬菜沙拉',
    description: '新鲜蔬菜搭配橄榄油醋汁，低卡健康',
    category: 'healthy',
    icon: 'fa-leaf',
    categoryName: '健康餐',
  },
  {
    name: '烤鸡胸肉',
    description: '低脂高蛋白的烤鸡胸肉，搭配烤蔬菜',
    category: 'healthy',
    icon: 'fa-fire',
    categoryName: '健康餐',
  },
  {
    name: '燕麦碗',
    description: '燕麦粥搭配新鲜水果、坚果和蜂蜜，营养丰富',
    category: 'healthy',
    icon: 'fa-leaf',
    categoryName: '健康餐',
  },
  {
    name: '水煮蛋',
    description: '鸡蛋水煮而成，保留营养，低脂高蛋白',
    category: 'healthy',
    icon: 'fa-cutlery',
    categoryName: '健康餐',
  },
  {
    name: '全麦面包',
    description: '富含膳食纤维的全麦面包，健康早餐选择',
    category: 'healthy',
    icon: 'fa-cutlery',
    categoryName: '健康餐',
  },
  {
    name: '蔬菜汤',
    description: '多种蔬菜熬制的汤品，低热量高营养',
    category: 'healthy',
    icon: 'fa-fire',
    categoryName: '健康餐',
  },
  {
    name: '清蒸鱼',
    description: '鱼肉清蒸而成，保留营养，低脂健康',
    category: 'healthy',
    icon: 'fa-cutlery',
    categoryName: '健康餐',
  },
  {
    name: '希腊酸奶',
    description: '高蛋白低乳糖的酸奶，可搭配水果食用',
    category: 'healthy',
    icon: 'fa-cutlery',
    categoryName: '健康餐',
  },
]
